---
linters:
  disable-all: false
  enable-all: true
  disable:
    - gci
    - gochecknoglobals
    - tagliatelle
    - exhaustivestruct
    - nolintlint
    - exhaustruct
    - forbidigo
    - paralleltest
    - cyclop
    - ireturn
    - wrapcheck
    - interfacebloat
    - forcetypeassert
    - dupl
    - goconst
    - maligned
    - depguard
    - tagalign
    - perfsprint

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd

    # https://github.com/go-critic/go-critic/issues/926
    - linters:
        - gocritic
      text: "unnecessaryDefer:"

linters-settings:
  funlen:
    lines: 160
    statements: 50

  lll:
    line-length: 165

  dupl:
    threshold: 450

  gocognit:
    min-complexity: 78

  nestif:
    min-complexity: 20


run:
  concurrency: 10
  timeout: 10m
  issues-exit-code: 1
  tests: true
  exclude-dirs:
    - scripts/
    - vendor/
    - docs/

  exclude-files:
    - Makefile
    - README.md
    - Dockerfile

severity:
  default-severity: error

service:
  golangci-lint-version: 1.27.x
  prepare:
    - make local.check